### ISSUE TITLE
nf-validation

### ISSUE THREAD

**Issue by Emiller88** [nf-core/methylseq#339]
### Description of feature

Use all the nf-validation goodness.
```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/methylseq/pull/341
- [ ] https://github.com/nf-core/methylseq/issues/337
- [ ] https://github.com/nf-core/methylseq/pull/342
```
